pipeline{
    
    agent any
    
    stages{

        stage("build"){
            steps{
                sh 'mvn clean install -f java-tomcat-sample/pom.xml'
            }
        }
        
        stage("archive"){
            steps{
                 archiveArtifacts artifacts: '**/*.war', followSymlinks: false
            }
        }
        
        stage("Shell Message"){
            steps{
                sh 'echo "Checkout Done, build has been completed and Archived the Artifacts"'
            }
        }
        
        stage("Tomcat NPD"){
            steps{
                deploy adapters: [tomcat8(credentialsId: '0978a95b-a4a4-4201-afa2-56076c05d01c', path: '', url: 'http://168.61.33.139:8080/webapp')], contextPath: null, onFailure: false, war: '**/*.war'
            }
        }
        
        stage("NPD Shell Message"){
            steps{
                sh 'echo "deployment completed at `date`"'
            }
        }
        
        stage("Tomcat PD"){
            steps{
                deploy adapters: [tomcat8(credentialsId: '0978a95b-a4a4-4201-afa2-56076c05d01c', path: '', url: 'http://168.61.33.139:8081/webapp/')], contextPath: null, onFailure: false, war: '**/*.war'
            }
        }
        
        stage("PD Shell Message"){
            steps{
                sh 'echo "Production deployment completed at `date`"'
            }
            
        }
    }
}
